export interface CityConfig {
  slug: string;
  name: string;
  station: string;
  icao: string;
  timezone: string;
  polySlug: string;
  lat: number;
  lon: number;
  preferredUnit: "C" | "F";
}

export const CITIES: CityConfig[] = [
  {
    slug: "new-york",
    name: "New York",
    station: "KLGA:9:US",
    icao: "KLGA",
    timezone: "America/New_York",
    polySlug: "nyc",
    lat: 40.7769,
    lon: -73.8740,
    preferredUnit: "F",
  },
  {
    slug: "chicago",
    name: "Chicago",
    station: "KORD:9:US",
    icao: "KORD",
    timezone: "America/Chicago",
    polySlug: "chicago",
    lat: 41.9742,
    lon: -87.9073,
    preferredUnit: "F",
  },
  {
    slug: "seattle",
    name: "Seattle",
    station: "KSEA:9:US",
    icao: "KSEA",
    timezone: "America/Los_Angeles",
    polySlug: "seattle",
    lat: 47.4502,
    lon: -122.3088,
    preferredUnit: "F",
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    station: "KSFO:9:US",
    icao: "KSFO",
    timezone: "America/Los_Angeles",
    polySlug: "san-francisco",
    lat: 37.6213,
    lon: -122.3790,
    preferredUnit: "F",
  },
  {
    slug: "london",
    name: "London",
    station: "EGLC:9:GB",
    icao: "EGLC",
    timezone: "Europe/London",
    polySlug: "london",
    lat: 51.5053,
    lon: 0.0553,
    preferredUnit: "C",
  },
  {
    slug: "seoul",
    name: "Seoul",
    station: "RKSI:9:KR",
    icao: "RKSI",
    timezone: "Asia/Seoul",
    polySlug: "seoul",
    lat: 37.4602,
    lon: 126.4407,
    preferredUnit: "C",
  },
  {
    slug: "buenos-aires",
    name: "Buenos Aires",
    station: "SAEZ:9:AR",
    icao: "SAEZ",
    timezone: "America/Argentina/Buenos_Aires",
    polySlug: "buenos-aires",
    lat: -34.8222,
    lon: -58.5358,
    preferredUnit: "C",
  },
  {
    slug: "singapore",
    name: "Singapore",
    station: "WSSS:9:SG",
    icao: "WSSS",
    timezone: "Asia/Singapore",
    polySlug: "singapore",
    lat: 1.3644,
    lon: 103.9915,
    preferredUnit: "C",
  },
  {
    slug: "austin",
    name: "Austin",
    station: "KAUS:9:US",
    icao: "KAUS",
    timezone: "America/Chicago",
    polySlug: "austin",
    lat: 30.1945,
    lon: -97.6699,
    preferredUnit: "F",
  },
  {
    slug: "shanghai",
    name: "Shanghai",
    station: "ZSPD:9:CN",
    icao: "ZSPD",
    timezone: "Asia/Shanghai",
    polySlug: "shanghai",
    lat: 31.1433,
    lon: 121.8053,
    preferredUnit: "C",
  },
  {
    slug: "tokyo",
    name: "Tokyo",
    station: "RJTT:9:JP",
    icao: "RJTT",
    timezone: "Asia/Tokyo",
    polySlug: "tokyo",
    lat: 35.5497,
    lon: 139.7870,
    preferredUnit: "C",
  },
  {
    slug: "mexico-city",
    name: "Mexico City",
    station: "MMMX:9:MX",
    icao: "MMMX",
    timezone: "America/Mexico_City",
    polySlug: "mexico-city",
    lat: 19.4361,
    lon: -99.0719,
    preferredUnit: "C",
  },
  {
    slug: "shenzhen",
    name: "Shenzhen",
    station: "ZGSZ:9:CN",
    icao: "ZGSZ",
    timezone: "Asia/Shanghai",
    polySlug: "shenzhen",
    lat: 22.6395,
    lon: 113.8033,
    preferredUnit: "C",
  },
  {
    slug: "wellington",
    name: "Wellington",
    station: "NZWN:9:NZ",
    icao: "NZWN",
    timezone: "Pacific/Auckland",
    polySlug: "wellington",
    lat: -41.3268,
    lon: 174.8069,
    preferredUnit: "C",
  },
  {
    slug: "toronto",
    name: "Toronto",
    station: "CYYZ:9:CA",
    icao: "CYYZ",
    timezone: "America/Toronto",
    polySlug: "toronto",
    lat: 43.6772,
    lon: -79.6306,
    preferredUnit: "C",
  },
  {
    slug: "milan",
    name: "Milan",
    station: "LIMC:9:IT",
    icao: "LIMC",
    timezone: "Europe/Rome",
    polySlug: "milan",
    lat: 45.6306,
    lon: 8.7281,
    preferredUnit: "C",
  },
  {
    slug: "dallas",
    name: "Dallas",
    station: "KDAL:9:US",
    icao: "KDAL",
    timezone: "America/Chicago",
    polySlug: "dallas",
    lat: 32.8459,
    lon: -96.8509,
    preferredUnit: "F",
  },
  {
    slug: "lucknow",
    name: "Lucknow",
    station: "VILK:9:IN",
    icao: "VILK",
    timezone: "Asia/Kolkata",
    polySlug: "lucknow",
    lat: 26.7606,
    lon: 80.8903,
    preferredUnit: "C",
  },
  {
    slug: "beijing",
    name: "Beijing",
    station: "ZBAA:9:CN",
    icao: "ZBAA",
    timezone: "Asia/Shanghai",
    polySlug: "beijing",
    lat: 40.0773,
    lon: 116.5967,
    preferredUnit: "C",
  },
  {
    slug: "ankara",
    name: "Ankara",
    station: "LTAC:9:TR",
    icao: "LTAC",
    timezone: "Europe/Istanbul",
    polySlug: "ankara",
    lat: 40.1281,
    lon: 32.9950,
    preferredUnit: "C",
  },
  {
    slug: "madrid",
    name: "Madrid",
    station: "LEMD:9:ES",
    icao: "LEMD",
    timezone: "Europe/Madrid",
    polySlug: "madrid",
    lat: 40.4933,
    lon: -3.5681,
    preferredUnit: "C",
  },
  {
    slug: "taipei",
    name: "Taipei",
    station: "RCSS:9:TW",
    icao: "RCSS",
    timezone: "Asia/Taipei",
    polySlug: "taipei",
    lat: 25.0697,
    lon: 121.5525,
    preferredUnit: "C",
  },
  {
    slug: "paris",
    name: "Paris",
    station: "LFPB:9:FR",
    icao: "LFPB",
    timezone: "Europe/Paris",
    polySlug: "paris",
    lat: 48.9697,
    lon: 2.4417,
    preferredUnit: "C",
  },
  {
    slug: "munich",
    name: "Munich",
    station: "EDDM:9:DE",
    icao: "EDDM",
    timezone: "Europe/Berlin",
    polySlug: "munich",
    lat: 48.3536,
    lon: 11.7861,
    preferredUnit: "C",
  },
  {
    slug: "miami",
    name: "Miami",
    station: "KMIA:9:US",
    icao: "KMIA",
    timezone: "America/New_York",
    polySlug: "miami",
    lat: 25.7954,
    lon: -80.2901,
    preferredUnit: "F",
  },
  {
    slug: "houston",
    name: "Houston",
    station: "KHOU:9:US",
    icao: "KHOU",
    timezone: "America/Chicago",
    polySlug: "houston",
    lat: 29.6458,
    lon: -95.2772,
    preferredUnit: "F",
  },
  {
    slug: "atlanta",
    name: "Atlanta",
    station: "KATL:9:US",
    icao: "KATL",
    timezone: "America/New_York",
    polySlug: "atlanta",
    lat: 33.6367,
    lon: -84.4281,
    preferredUnit: "F",
  },
  {
    slug: "denver",
    name: "Denver",
    station: "KBKF:9:US",
    icao: "KBKF",
    timezone: "America/Denver",
    polySlug: "denver",
    lat: 39.7018,
    lon: -104.7520,
    preferredUnit: "F",
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    station: "KLAX:9:US",
    icao: "KLAX",
    timezone: "America/Los_Angeles",
    polySlug: "los-angeles",
    lat: 33.9425,
    lon: -118.4081,
    preferredUnit: "F",
  },
  {
    slug: "chongqing",
    name: "Chongqing",
    station: "ZUCK:9:CN",
    icao: "ZUCK",
    timezone: "Asia/Shanghai",
    polySlug: "chongqing",
    lat: 29.7123,
    lon: 106.6519,
    preferredUnit: "C",
  },
  {
    slug: "chengdu",
    name: "Chengdu",
    station: "ZUUU:9:CN",
    icao: "ZUUU",
    timezone: "Asia/Shanghai",
    polySlug: "chengdu",
    lat: 30.5583,
    lon: 103.9460,
    preferredUnit: "C",
  },
  {
    slug: "manila",
    name: "Manila",
    station: "RPLL:9:PH",
    icao: "RPLL",
    timezone: "Asia/Manila",
    polySlug: "manila",
    lat: 14.5086,
    lon: 121.0200,
    preferredUnit: "C",
  },
  {
    slug: "helsinki",
    name: "Helsinki",
    station: "EFHK:9:FI",
    icao: "EFHK",
    timezone: "Europe/Helsinki",
    polySlug: "helsinki",
    lat: 60.3172,
    lon: 24.9633,
    preferredUnit: "C",
  },
  {
    slug: "warsaw",
    name: "Warsaw",
    station: "EPWA:9:PL",
    icao: "EPWA",
    timezone: "Europe/Warsaw",
    polySlug: "warsaw",
    lat: 52.1657,
    lon: 20.9671,
    preferredUnit: "C",
  },
  {
    slug: "guangzhou",
    name: "Guangzhou",
    station: "ZGGG:9:CN",
    icao: "ZGGG",
    timezone: "Asia/Shanghai",
    polySlug: "guangzhou",
    lat: 23.3925,
    lon: 113.2990,
    preferredUnit: "C",
  },
  {
    slug: "wuhan",
    name: "Wuhan",
    station: "ZHHH:9:CN",
    icao: "ZHHH",
    timezone: "Asia/Shanghai",
    polySlug: "wuhan",
    lat: 30.7748,
    lon: 114.2137,
    preferredUnit: "C",
  },
  {
    slug: "cape-town",
    name: "Cape Town",
    station: "FACT:9:ZA",
    icao: "FACT",
    timezone: "Africa/Johannesburg",
    polySlug: "cape-town",
    lat: -33.9694,
    lon: 18.5972,
    preferredUnit: "C",
  },
  {
    slug: "amsterdam",
    name: "Amsterdam",
    station: "EHAM:9:NL",
    icao: "EHAM",
    timezone: "Europe/Amsterdam",
    polySlug: "amsterdam",
    lat: 52.3086,
    lon: 4.7639,
    preferredUnit: "C",
  },
  {
    slug: "lagos",
    name: "Lagos",
    station: "DNMM:9:NG",
    icao: "DNMM",
    timezone: "Africa/Lagos",
    polySlug: "lagos",
    lat: 6.5774,
    lon: 3.3212,
    preferredUnit: "C",
  },
  {
    slug: "panama",
    name: "Panama",
    station: "MPMG:9:PA",
    icao: "MPMG",
    timezone: "America/Panama",
    polySlug: "panama-city",
    lat: 8.9733,
    lon: -79.5550,
    preferredUnit: "C",
  },
  {
    slug: "jeddah",
    name: "Jeddah",
    station: "OEJN:9:SA",
    icao: "OEJN",
    timezone: "Asia/Riyadh",
    polySlug: "jeddah",
    lat: 21.6802,
    lon: 39.1574,
    preferredUnit: "C",
  },
  {
    slug: "busan",
    name: "Busan",
    station: "RKPK:9:KR",
    icao: "RKPK",
    timezone: "Asia/Seoul",
    polySlug: "busan",
    lat: 35.1795,
    lon: 128.9380,
    preferredUnit: "C",
  },
  {
    slug: "sao-paulo",
    name: "Sao Paulo",
    station: "SBGR:9:BR",
    icao: "SBGR",
    timezone: "America/Sao_Paulo",
    polySlug: "sao-paulo",
    lat: -23.4313,
    lon: -46.4700,
    preferredUnit: "C",
  },
  {
    slug: "karachi",
    name: "Karachi",
    station: "OPKC:9:PK",
    icao: "OPKC",
    timezone: "Asia/Karachi",
    polySlug: "karachi",
    lat: 24.9065,
    lon: 67.1608,
    preferredUnit: "C",
  },
  {
    slug: "jakarta",
    name: "Jakarta",
    station: "WIHH:9:ID",
    icao: "WIHH",
    timezone: "Asia/Jakarta",
    polySlug: "jakarta",
    lat: -6.2670,
    lon: 106.8903,
    preferredUnit: "C",
  },
  {
    slug: "kuala-lumpur",
    name: "Kuala Lumpur",
    station: "WMKK:9:MY",
    icao: "WMKK",
    timezone: "Asia/Kuala_Lumpur",
    polySlug: "kuala-lumpur",
    lat: 2.7456,
    lon: 101.7100,
    preferredUnit: "C",
  },
];

export const getCityBySlug = (slug: string) => {
  return CITIES.find((c) => c.slug === slug);
};
